# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UOpUmhfcv8YRZ6-QgTFtAab7ZuGTY6zP
"""

!pip install tensorflow numpy matplotlib scikit-learn seaborn --quiet

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

import tensorflow as tf
from tensorflow.keras.models import Model

from tensorflow.keras.layers import (
    Input, Conv1D, MaxPooling1D, BatchNormalization,
    Dropout, Dense, LayerNormalization, MultiHeadAttention,
    GlobalAveragePooling1D, Add, Concatenate, Lambda   # ← add Lambda
)

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import (
    EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
)

print("TF version :", tf.__version__)
print("GPU        :", tf.config.list_physical_devices('GPU'))

SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)

from google.colab import drive
drive.mount('/content/gdrive')

# ── TRY TO DOWNLOAD TAGS CSV DIRECTLY ────────────────────────────────
import urllib.request
import os

csv_url  = ('http://www.panoradio-sdr.de/wp-content/'
            'uploads/dataset_panoradio_hf_tags.csv')
csv_path = '/content/dataset_panoradio_hf_tags.csv'

print("Attempting to download tags CSV...")
try:
    urllib.request.urlretrieve(csv_url, csv_path)
    file_size = os.path.getsize(csv_path)
    print(f"✅ Downloaded successfully: {file_size} bytes")
except Exception as e:
    print(f"❌ Download failed: {e}")
    print("Try manual download from browser")

# ── USE CSV TO GET EXACT LABELS ───────────────────────────────────────
import pandas as pd

csv_path = '/content/dataset_panoradio_hf_tags.csv'

# Load CSV
tags = pd.read_csv(csv_path)
print("CSV shape    :", tags.shape)
print("CSV columns  :", tags.columns.tolist())
print("First 5 rows :")
print(tags.head())
print("\nLast 5 rows  :")
print(tags.tail())

# ── REBUILD LABELS FROM CSV — COMPLETE FIX ───────────────────────────
import pandas as pd
import numpy as np

# ── Step 1: Load CSV with correct column names ────────────────────────
csv_path = '/content/dataset_panoradio_hf_tags.csv'
tags     = pd.read_csv(csv_path)

# Strip spaces from column names
tags.columns = tags.columns.str.strip()
print("Columns after strip:", tags.columns.tolist())
print("Shape:", tags.shape)
print()
print("First 5 rows:")
print(tags.head())
print()
print("Unique modes:", sorted(tags['mode'].unique()))
print("Unique SNRs :", sorted(tags['snr'].unique()))

# ── Step 2: Define MODE_NAMES matching CSV mode names ─────────────────
# CSV uses: dominoex11 — we need to check exact names
csv_modes = sorted(tags['mode'].unique())
print("\nCSV mode names (exact):")
for m in csv_modes:
    print(f"    '{m}'")

# ── Step 3: Map CSV names to our class indices ────────────────────────

# CSV mode names exactly as they appear
# Map each to our class index
CSV_MODE_TO_IDX = {
    'morse'         : 0,
    'psk31'         : 1,
    'psk63'         : 2,
    'qpsk31'        : 3,
    'rtty45_170'    : 4,
    'rtty50_170'    : 5,
    'rtty100_850'   : 6,
    'olivia8_250'   : 7,
    'olivia16_500'  : 8,
    'olivia16_1000' : 9,
    'olivia32_1000' : 10,
    'dominoex11'    : 11,   # ← CSV uses dominoex11 not dominoex
    'mt63_1000'     : 12,
    'navtex'        : 13,
    'usb'           : 14,
    'lsb'           : 15,
    'am'            : 16,
    'fax'           : 17,
}

# Our display names (for plots and reports)
MODE_NAMES = [
    'morse', 'psk31', 'psk63', 'qpsk31',
    'rtty45_170', 'rtty50_170', 'rtty100_850',
    'olivia8_250', 'olivia16_500', 'olivia16_1000', 'olivia32_1000',
    'dominoex', 'mt63_1000', 'navtex',
    'usb', 'lsb', 'am', 'fax'
]

# ── Step 4: Build labels directly from CSV ────────────────────────────
print("Building labels from CSV...")

labels_class_csv = []
labels_snr_csv   = []
errors           = []

for i in range(len(tags)):
    mode_name = tags.iloc[i]['mode'].strip()
    snr_val   = int(tags.iloc[i]['snr'])

    if mode_name in CSV_MODE_TO_IDX:
        labels_class_csv.append(CSV_MODE_TO_IDX[mode_name])
    else:
        errors.append(f"Row {i}: unknown mode '{mode_name}'")
        labels_class_csv.append(-1)

    labels_snr_csv.append(snr_val)

labels_class = np.array(labels_class_csv, dtype=np.int32)
labels_snr   = np.array(labels_snr_csv,   dtype=np.int32)

if errors:
    print(f"⚠️  {len(errors)} unknown modes found:")
    for e in errors[:5]:
        print(f"    {e}")
else:
    print("✅ All modes mapped successfully")

print(f"\nLabels built:")
print(f"    Total samples : {len(labels_class)}")
print(f"    Unique classes: {sorted(np.unique(labels_class))}")
print(f"    Unique SNRs   : {sorted(np.unique(labels_snr))}")

# ── Step 5: Verify first and last 5 rows ──────────────────────────────
print("\nFirst 5 label assignments:")
print(f"{'Row':>6} {'CSV mode':>16} {'CSV SNR':>8} "
      f"{'Class idx':>10} {'Our name':>16}")
print("-" * 62)
for i in range(5):
    csv_mode = tags.iloc[i]['mode'].strip()
    csv_snr  = int(tags.iloc[i]['snr'])
    cls_idx  = labels_class[i]
    our_name = MODE_NAMES[cls_idx] if cls_idx >= 0 else 'ERROR'
    print(f"{i:>6} {csv_mode:>16} {csv_snr:>8} "
          f"{cls_idx:>10} {our_name:>16}")

print("\nLast 5 label assignments:")
print(f"{'Row':>6} {'CSV mode':>16} {'CSV SNR':>8} "
      f"{'Class idx':>10} {'Our name':>16}")
print("-" * 62)
for i in range(len(tags)-5, len(tags)):
    csv_mode = tags.iloc[i]['mode'].strip()
    csv_snr  = int(tags.iloc[i]['snr'])
    cls_idx  = labels_class[i]
    our_name = MODE_NAMES[cls_idx] if cls_idx >= 0 else 'ERROR'
    print(f"{i:>6} {csv_mode:>16} {csv_snr:>8} "
          f"{cls_idx:>10} {our_name:>16}")

# ── All constants defined AFTER CSV labels ────────────────────────────
NUM_CLASSES = 18
IQ_LENGTH   = 2048

# SNR values directly from CSV — ground truth
SNR_VALUES = sorted(np.unique(labels_snr).tolist())

# Display names for plots and reports
MODE_NAMES = [
    'morse', 'psk31', 'psk63', 'qpsk31',
    'rtty45_170', 'rtty50_170', 'rtty100_850',
    'olivia8_250', 'olivia16_500', 'olivia16_1000', 'olivia32_1000',
    'dominoex', 'mt63_1000', 'navtex',
    'usb', 'lsb', 'am', 'fax'
]

print(f"NUM_CLASSES : {NUM_CLASSES}")
print(f"IQ_LENGTH   : {IQ_LENGTH}")
print(f"SNR_VALUES  : {SNR_VALUES}")
print(f"MODE_NAMES  : {MODE_NAMES}")

# Confirm labels match expected counts
print("\nSamples per class:")
for cls in range(NUM_CLASSES):
    count = np.sum(labels_class == cls)
    print(f"  {MODE_NAMES[cls]:>20} : {count}")

print("\nSamples per SNR:")
for snr in SNR_VALUES:
    count = np.sum(labels_snr == snr)
    print(f"  SNR {snr:>4} dB : {count}")

# ── UPDATE THIS PATH ──────────────────────────────────────────────────
DATASET_PATH = '/content/gdrive/MyDrive/panoradio_dataset/dataset_panoradio_hf.npy'

print("Loading dataset...")
t0       = time.time()
raw_data = np.load(DATASET_PATH)
print(f"Done in {time.time()-t0:.1f}s")
print(f"Shape : {raw_data.shape}")
print(f"Dtype : {raw_data.dtype}")

assert raw_data.shape[0] == 172800, \
    f"Expected 172800 rows, got {raw_data.shape[0]}"
print("✅ Row count correct")

# print("Converting complex → [I, Q] float32...")
# t0 = time.time()

# I = raw_data.real.astype(np.float32)
# Q = raw_data.imag.astype(np.float32)

# power = np.sqrt(np.mean(I**2 + Q**2, axis=1, keepdims=True))
# power = np.where(power < 1e-10, 1.0, power)
# I    /= power
# Q    /= power

# X = np.stack([I, Q], axis=-1)   # (172800, 2048, 2)

# print(f"Done in {time.time()-t0:.1f}s")
# print(f"X shape : {X.shape}")
# print(f"X dtype : {X.dtype}")

# del raw_data, I, Q
# import gc; gc.collect()
# print("Raw data freed.")
print("Converting complex → [I,Q] float32...")
t0 = time.time()

# Create final tensor directly (avoids storing I and Q separately)
X = np.empty(
    (raw_data.shape[0], raw_data.shape[1], 2),
    dtype=np.float32
)

# Fill I and Q channels
X[..., 0] = raw_data.real
X[..., 1] = raw_data.imag

# Free complex array immediately
del raw_data

import gc
gc.collect()

# RMS power normalization
power = np.sqrt(
    np.mean(
        X[..., 0]**2 + X[..., 1]**2,
        axis=1,
        keepdims=True
    )
).astype(np.float32)

power = np.maximum(power, 1e-10)

X[..., 0] /= power
X[..., 1] /= power

del power
gc.collect()

print(f"Done in {time.time()-t0:.1f}s")
print(f"X shape : {X.shape}")
print(f"X dtype : {X.dtype}")
print(f"RAM used by X : {X.nbytes / (1024**3):.2f} GB")
print("Raw data freed.")

y = to_categorical(labels_class, num_classes=NUM_CLASSES)

# 70% train, 15% val, 15% test
X_train, X_temp, y_train, y_temp, snr_train, snr_temp = \
    train_test_split(
        X, y, labels_snr,
        test_size=0.30,
        random_state=SEED,
        stratify=labels_class
    )

y_temp_idx = np.argmax(y_temp, axis=1)
X_val, X_test, y_val, y_test, snr_val, snr_test = \
    train_test_split(
        X_temp, y_temp, snr_temp,
        test_size=0.50,
        random_state=SEED,
        stratify=y_temp_idx
    )

print(f"Train : {X_train.shape}")
print(f"Val   : {X_val.shape}")
print(f"Test  : {X_test.shape}")

# Verify distributions
print("\nSNR distribution in test set:")
snr_u, snr_c = np.unique(snr_test, return_counts=True)
expected      = int(len(snr_test) / 8)
for snr, cnt in zip(snr_u, snr_c):
    status = "✅" if abs(cnt - expected) < 100 else "⚠️"
    print(f"  SNR {snr:>4} dB : {cnt}  {status}")

print("\nClass distribution in test set:")
cls_u, cls_c = np.unique(np.argmax(y_test, axis=1),
                          return_counts=True)
for cls, cnt in zip(cls_u, cls_c):
    status = "✅" if cnt == 1440 else "⚠️"
    print(f"  {MODE_NAMES[cls]:>20} : {cnt}  {status}")

class AttentionPooling(tf.keras.layers.Layer):
    """
    Learnable attention pooling.

    Instead of averaging all timesteps equally,
    it learns which timesteps matter most for
    classification and weights them accordingly.

    This is better than mean pooling for RF signals
    because symbol transitions and fading events
    at specific timesteps carry more information.
    """
    def __init__(self, d_model, **kwargs):
        super().__init__(**kwargs)
        self.dense1 = Dense(d_model, activation='tanh')
        self.dense2 = Dense(1)

    def call(self, x):
        # x: (batch, seq_len, d_model)
        e     = self.dense1(x)              # (batch, seq_len, d_model)
        e     = self.dense2(e)              # (batch, seq_len, 1)
        alpha = tf.nn.softmax(e, axis=1)    # (batch, seq_len, 1)
        out   = tf.reduce_sum(alpha * x, axis=1)  # (batch, d_model)
        return out

print("AttentionPooling layer defined.")

def transformer_encoder_block(x, d_model, num_heads, ff_dim,
                               dropout_rate=0.2, name_prefix=''):
    """
    Single Transformer encoder block:
        Multi-Head Self-Attention → Add & LayerNorm
        Feed-Forward Network      → Add & LayerNorm

    Identical to the standalone Transformer model
    so comparison is completely fair.
    """
    # Multi-Head Self-Attention
    attn = MultiHeadAttention(
        num_heads=num_heads,
        key_dim=d_model // num_heads,
        dropout=dropout_rate,
        name=f'{name_prefix}_mha'
    )(x, x)
    attn = Dropout(dropout_rate,  name=f'{name_prefix}_drop1')(attn)
    x    = Add(                   name=f'{name_prefix}_add1')([x, attn])
    x    = LayerNormalization(    name=f'{name_prefix}_ln1')(x)

    # Feed-Forward Network
    ffn  = Dense(ff_dim, activation='relu', name=f'{name_prefix}_ffn1')(x)
    ffn  = Dropout(dropout_rate,            name=f'{name_prefix}_drop2')(ffn)
    ffn  = Dense(d_model,                   name=f'{name_prefix}_ffn2')(ffn)
    ffn  = Dropout(dropout_rate,            name=f'{name_prefix}_drop3')(ffn)
    x    = Add(                             name=f'{name_prefix}_add2')([x, ffn])
    x    = LayerNormalization(              name=f'{name_prefix}_ln2')(x)

    return x

print("Transformer encoder block defined.")

def get_positional_encoding(seq_len, d_model):
    """
    Sinusoidal positional encoding.
    Same as Vaswani et al. (2017) Attention is All You Need.
    Returns tensor of shape (1, seq_len, d_model).
    """
    positions = np.arange(seq_len)[:, np.newaxis]
    dims      = np.arange(d_model)[np.newaxis, :]
    angles    = positions / np.power(
        10000, (2 * (dims // 2)) / np.float32(d_model)
    )
    angles[:, 0::2] = np.sin(angles[:, 0::2])
    angles[:, 1::2] = np.cos(angles[:, 1::2])
    return tf.cast(angles[np.newaxis, :, :], dtype=tf.float32)

print("Positional encoding defined.")

from tensorflow.keras.layers import (
    Input, Conv1D, MaxPooling1D, BatchNormalization,
    Dropout, Dense, LayerNormalization, MultiHeadAttention,
    LSTM, Bidirectional, Add, Concatenate, GlobalAveragePooling1D
)

def build_cnn_fusion_model(input_length=2048, n_channels=2,
                            n_classes=18,
                            lstm_units=128,
                            d_model=128, num_heads=8,
                            ff_dim=256, num_transformer_blocks=3,
                            dropout_rate=0.3):
    """
    CNN + BiLSTM + Transformer + Bidirectional Cross-Attention Fusion

    Architecture
    ------------
    Input (2048, 2)
        ↓
    Shared CNN frontend  →  compress (2048,2) to (32,256)
        ↓              ↓
    BiLSTM branch    Transformer branch
    H_LSTM (32,256)  H_Trans (32,128)
        ↓              ↓
    Project both to same dimension (32, 128)
        ↓
    Cross-Attention Direction 1:
        Q = H_Trans,  K/V = H_LSTM_proj
        "Transformer queries LSTM for local patterns"
        ↓
    Cross-Attention Direction 2:
        Q = H_LSTM,   K/V = H_Trans
        "LSTM queries Transformer for global context"
        ↓
    BatchNorm on both fusion outputs
        ↓
    AttentionPool(Fusion_1) + AttentionPool(Fusion_2)
        ↓
    Concatenate → Dense → Dropout → Softmax (18)

    Fixes from DDP Stage 1 CAFT
    ----------------------------
    1. CNN frontend added          (Stage 1 had none)
    2. Explicit dimension projection  (Stage 1 had mismatch)
    3. Bidirectional cross-attention  (Stage 1 was one-way)
    4. BatchNorm before fusion     (Stage 1 had none)
    5. Attention pooling           (Stage 1 used mean pool)
    6. Balanced concatenation      (Stage 1 double-counted LSTM)
    """

    inp = Input(shape=(input_length, n_channels), name='iq_input')

    # ── SHARED CNN frontend ───────────────────────────────────────────
    # Identical to standalone CNN-BiLSTM and CNN-Transformer models
    # Both branches see the same compressed representation
    # This ensures fair comparison

    # Block 1: 2048 → 512
    x = Conv1D(64,  kernel_size=7, padding='same',
               activation='relu', name='conv1')(inp)
    x = BatchNormalization(name='bn_cnn1')(x)
    x = MaxPooling1D(pool_size=4, name='pool1')(x)
    x = Dropout(dropout_rate * 0.5, name='drop_cnn1')(x)

    # Block 2: 512 → 128
    x = Conv1D(128, kernel_size=5, padding='same',
               activation='relu', name='conv2')(x)
    x = BatchNormalization(name='bn_cnn2')(x)
    x = MaxPooling1D(pool_size=4, name='pool2')(x)
    x = Dropout(dropout_rate * 0.5, name='drop_cnn2')(x)

    # Block 3: 128 → 32
    x = Conv1D(256, kernel_size=3, padding='same',
               activation='relu', name='conv3')(x)
    x = BatchNormalization(name='bn_cnn3')(x)
    x = MaxPooling1D(pool_size=4, name='pool3')(x)
    x = Dropout(dropout_rate * 0.5, name='drop_cnn3')(x)
    # x shape now: (batch, 32, 256)

    # ── NEW BRANCH 3: Phase-State Detector ─────────────────────────────
    # Distinguishes 2-phase (PSK) from 4-phase (QPSK) signals
    # by analysing the instantaneous phase distribution directly

    def compute_phase(inputs):
        I = inputs[:, :, 0:1]
        Q = inputs[:, :, 1:2]
        return tf.atan2(Q, I)   # (batch, 2048, 1)

    phase_signal = Lambda(
        compute_phase,
        output_shape=(input_length, 1),
        name='phase_signal'
    )(inp)

    p = MaxPooling1D(pool_size=4, name='phase_pool1')(phase_signal)
    p = Conv1D(32, kernel_size=9, padding='same',
               activation='relu', name='phase_conv1')(p)
    p = BatchNormalization(name='phase_bn1')(p)
    p = MaxPooling1D(pool_size=4, name='phase_pool2')(p)
    p = Conv1D(64, kernel_size=5, padding='same',
               activation='relu', name='phase_conv2')(p)
    p = BatchNormalization(name='phase_bn2')(p)
    phase_features = GlobalAveragePooling1D(name='phase_gap')(p)
    # phase_features shape: (batch, 64)


    # ── BRANCH 1: BiLSTM ──────────────────────────────────────────────
    # Captures local temporal patterns
    # Symbol timing, baud rate, short-term correlations
    h_lstm = Bidirectional(
        LSTM(lstm_units, return_sequences=True, dropout=0.2),
        name='bilstm1'
    )(x)
    h_lstm = BatchNormalization(name='bn_lstm1')(h_lstm)
    h_lstm = Bidirectional(
        LSTM(lstm_units // 2, return_sequences=True, dropout=0.2),
        name='bilstm2'
    )(h_lstm)
    h_lstm = BatchNormalization(name='bn_lstm2')(h_lstm)
    # h_lstm shape: (batch, 32, lstm_units) = (batch, 32, 128)

    # ── BRANCH 2: Transformer ─────────────────────────────────────────
    # Captures global context and long-range dependencies
    # Channel behavior, fading patterns across the segment

    # Linear projection + positional encoding
    h_trans = Dense(d_model, name='trans_proj')(x)  # (batch, 32, 128)
    seq_len  = h_trans.shape[1]
    pos_enc  = get_positional_encoding(seq_len, d_model)
    h_trans  = h_trans + pos_enc

    # Transformer encoder blocks
    for i in range(num_transformer_blocks):
        h_trans = transformer_encoder_block(
            h_trans,
            d_model=d_model,
            num_heads=num_heads,
            ff_dim=ff_dim,
            dropout_rate=dropout_rate,
            name_prefix=f'trans_block{i+1}'
        )
    # h_trans shape: (batch, 32, 128)

    # ── DIMENSION ALIGNMENT ───────────────────────────────────────────
    # Fix DDP Stage 1 Mistake 1: explicit projection to same dimension
    # h_lstm  = (batch, 32, 128)  ← already 128 from BiLSTM(64)×2
    # h_trans = (batch, 32, 128)  ← d_model=128
    # Both are now same dimension — no implicit mismatch

    h_lstm_proj  = Dense(d_model, name='lstm_proj')(h_lstm)
    # h_lstm_proj: (batch, 32, 128)

    # ── BIDIRECTIONAL CROSS-ATTENTION ─────────────────────────────────
    # Fix DDP Stage 1 Mistake 3: add both directions

    # Direction 1: Transformer queries LSTM
    # "Global context asking about local patterns"
    # Q = H_Trans asks: "what local features from LSTM are relevant?"
    cross_attn_1 = MultiHeadAttention(
        num_heads=num_heads,
        key_dim=d_model // num_heads,
        dropout=dropout_rate,
        name='cross_attn_trans_queries_lstm'
    )(
        query=h_trans,       # Transformer features ask the questions
        key=h_lstm_proj,     # LSTM features provide the keys
        value=h_lstm_proj    # LSTM features provide the values
    )
    # Fix DDP Stage 1 Mistake 4: BatchNorm after each cross-attention
    cross_attn_1 = BatchNormalization(name='bn_cross1')(cross_attn_1)
    # cross_attn_1 shape: (batch, 32, 128)

    # Direction 2: LSTM queries Transformer
    # "Local patterns asking about global context"
    # Q = H_LSTM asks: "what global features from Transformer are relevant?"
    cross_attn_2 = MultiHeadAttention(
        num_heads=num_heads,
        key_dim=d_model // num_heads,
        dropout=dropout_rate,
        name='cross_attn_lstm_queries_trans'
    )(
        query=h_lstm_proj,   # LSTM features ask the questions
        key=h_trans,         # Transformer features provide the keys
        value=h_trans        # Transformer features provide the values
    )
    cross_attn_2 = BatchNormalization(name='bn_cross2')(cross_attn_2)
    # cross_attn_2 shape: (batch, 32, 128)

    # ── ATTENTION POOLING ─────────────────────────────────────────────
    # Fix DDP Stage 1 Mistake 3 + 5: attention pool, balanced branches
    # Direction 1 pooled: fused (Trans attended-to-LSTM) features
    # Direction 2 pooled: fused (LSTM attended-to-Trans) features
    pooled_1 = AttentionPooling(d_model, name='attn_pool_1')(cross_attn_1)
    pooled_2 = AttentionPooling(d_model, name='attn_pool_2')(cross_attn_2)
    # pooled_1: (batch, 128)
    # pooled_2: (batch, 128)

    # ── FUSION & CLASSIFICATION ───────────────────────────────────────
    # Fix DDP Stage 1 Mistake 2: balanced concatenation
    # pooled_1 = fused local+global (Trans queried LSTM)
    # pooled_2 = fused global+local (LSTM queried Trans)
    # No double-counting of either branch
    fused = Concatenate(name='concat_fusion')(
        [pooled_1, pooled_2, phase_features]   # ← add phase_features
    )
    # fused shape: (batch, 256 + 64) = (batch, 320)
    # fused shape: (batch, 256)

    fused = Dense(256, activation='relu', name='fc1')(fused)
    fused = Dropout(dropout_rate, name='drop_fc1')(fused)
    fused = Dense(128, activation='relu', name='fc2')(fused)
    fused = Dropout(dropout_rate * 0.5, name='drop_fc2')(fused)
    out   = Dense(n_classes, activation='softmax', name='output')(fused)

    model = Model(inputs=inp, outputs=out, name='CNN_Fusion_CAFT')
    return model


# ── Build model ───────────────────────────────────────────────────────
fusion_model = build_cnn_fusion_model(
    input_length=IQ_LENGTH,
    n_channels=2,
    n_classes=NUM_CLASSES,
    lstm_units=160,        # was 128
    d_model=160,            # was 128
    num_heads=8,
    ff_dim=320,              # was 256
    num_transformer_blocks=4,  # was 3
    dropout_rate=0.3
)

class_weights = {i: 1.0 for i in range(NUM_CLASSES)}
class_weights[1] = 1.3   # psk31
class_weights[2] = 1.3   # psk63
class_weights[3] = 1.4   # qpsk31 (weakest)
class_weights[16] = 1.2  # am

sample_weights_train = np.array(
    [class_weights[c] for c in np.argmax(y_train, axis=1)]
)

fusion_model.compile(
    optimizer=Adam(learning_rate=5e-4) ,  # instead of 1e-3
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

fusion_model.summary()

EPOCHS     = 100   # increase from 50
BATCH_SIZE = 64    # decrease for better gradient updates
PATIENCE   = 15    # give more time before stopping

# # Also reduce learning rate slightly
# optimizer=Adam(learning_rate=5e-4)  # instead of 1e-3

cb_fusion = [
    ModelCheckpoint(
        'best_fusion_panoradio.keras',
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    ),
    EarlyStopping(
        monitor='val_accuracy',
        patience=PATIENCE,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=4,
        min_lr=1e-6,
        verbose=1
    )
]

print("Training CNN-Fusion model ...")
t0 = time.time()

history_fusion = fusion_model.fit(
    X_train, y_train,
    sample_weight=sample_weights_train,   # ← add this
    batch_size=BATCH_SIZE,
    epochs=EPOCHS,
    validation_data=(X_val, y_val),
    callbacks=cb_fusion,
    verbose=1
)

print(f"\nTraining done in {(time.time()-t0)/60:.1f} min")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].plot(history_fusion.history['accuracy'],
             label='Train', color='green')
axes[0].plot(history_fusion.history['val_accuracy'],
             label='Val',   color='coral')
axes[0].set_title('Fusion — Accuracy')
axes[0].set_xlabel('Epoch')
axes[0].legend(); axes[0].grid(True, alpha=0.3)

axes[1].plot(history_fusion.history['loss'],
             label='Train', color='green')
axes[1].plot(history_fusion.history['val_loss'],
             label='Val',   color='coral')
axes[1].set_title('Fusion — Loss')
axes[1].set_xlabel('Epoch')
axes[1].legend(); axes[1].grid(True, alpha=0.3)

plt.suptitle('CNN-Fusion (CAFT) — Panoradio HF',
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

test_loss, test_acc = fusion_model.evaluate(
    X_test, y_test, batch_size=BATCH_SIZE, verbose=0
)
print(f"Test Loss     : {test_loss:.4f}")
print(f"Test Accuracy : {test_acc*100:.2f}%\n")

y_pred_fusion = np.argmax(
    fusion_model.predict(X_test, batch_size=BATCH_SIZE, verbose=0),
    axis=1
)
y_true = np.argmax(y_test, axis=1)

print(classification_report(y_true, y_pred_fusion,
                             target_names=MODE_NAMES))

cm      = confusion_matrix(y_true, y_pred_fusion)
cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)

plt.figure(figsize=(14, 12))
sns.heatmap(cm_norm, annot=True, fmt='.2f', cmap='Greens',
            xticklabels=MODE_NAMES, yticklabels=MODE_NAMES,
            vmin=0, vmax=1, linewidths=0.5)
plt.xlabel('Predicted', fontsize=12)
plt.ylabel('True',      fontsize=12)
plt.title(f'CNN-Fusion — Confusion Matrix — Acc {test_acc*100:.1f}%',
          fontsize=13, fontweight='bold')
plt.xticks(rotation=45, ha='right', fontsize=9)
plt.yticks(rotation=0,  fontsize=9)
plt.tight_layout()
plt.show()

snr_acc_fusion = {}
for snr in sorted(SNR_VALUES):
    idx   = np.where(snr_test == snr)[0]
    y_hat = fusion_model.predict(
        X_test[idx], batch_size=BATCH_SIZE, verbose=0
    )
    acc   = np.mean(
        np.argmax(y_hat, axis=1) == np.argmax(y_test[idx], axis=1)
    )
    snr_acc_fusion[snr] = acc
    print(f"SNR {snr:+4d} dB  →  {acc*100:.1f}%")

import numpy as np
import matplotlib.pyplot as plt

# SNR values
snr = [-10, -5, 0, 5, 10, 15, 20, 25]

# Fusion model accuracies
acc = [0.908, 0.891, 0.907, 0.895, 0.914, 0.959, 0.960, 0.992]

plt.figure(figsize=(4.5, 3))

plt.plot(
    snr,
    acc,
    'o-',
    linewidth=1.2,
    markersize=4,
    label='CNN-Fusion (CAFT)'
)

plt.axhline(
    0.90,
    color='gray',
    linestyle='--',
    linewidth=1,
    alpha=0.8,
    label='90% line'
)

plt.title(
    'Accuracy vs SNR — CNN-Fusion',
    fontsize=10,
    fontweight='bold'
)

plt.xlabel('SNR (dB)', fontsize=8)
plt.ylabel('Accuracy', fontsize=8)

plt.xticks(snr, fontsize=7)
plt.yticks(np.arange(0, 1.1, 0.2), fontsize=7)

plt.ylim(0, 1.05)

plt.grid(True, alpha=0.3)

plt.legend(fontsize=7, loc='lower left')

plt.tight_layout()
plt.show()